### ISSUE TITLE
Performance disparity with different versions of Qiskit

### ISSUE THREAD

**Issue by Youngcius** [abclzr/vqe_tetris#1]
Hi there. Recently I was testing your code. I found the Qiskit O3 compilation procedure appended to your Tetris has different optimization effects under different Qiskit versions. Did you notice this phenomenon?

**Comment by Youngcius** [comment]
> Hi there. Recently I was testing your code. I found the Qiskit O3 compilation procedure appended to your Tetris has different optimization effects under different Qiskit versions. Did you notice this phenomenon?

Specifically, Qiskit 0.46.1 significantly outperforms Qiskit 0.43.2 and Qiskit  1.2.4 on my Linux OS.

**Comment by abclzr** [comment]
Thank you for pointing it out. I have no clue about this phenomenon. For fair comparisons, we stick to the same version of Qiskit O3 for all experiments. In theory, a different version of Qiskit's optimization shouldn't affect our conclusion, because Qiskit O3 would not observe the canceling opportunity in UCCSD. Could you please share your results here? What is the percentage of outperformance for Qiskit 0.46.1?

**Comment by Youngcius** [comment]
> Thank you for pointing it out. I have no clue about this phenomenon. For fair comparisons, we stick to the same version of Qiskit O3 for all experiments. In theory, a different version of Qiskit's optimization shouldn't affect our conclusion, because Qiskit O3 would not observe the canceling opportunity in UCCSD. Could you please share your results here? What is the percentage of outperformance for Qiskit 0.46.1?

Sure. Can I share my testing results to your email? Previously I guessed it is OS-related disparity when I run it on Windows and Linux. Now I believe it is Qiskit version-related disparity QAQ.

**Comment by abclzr** [comment]
Yes, please. You can find my email on my homepage.

**Comment by abclzr** [comment]
> > Thank you for pointing it out. I have no clue about this phenomenon. For fair comparisons, we stick to the same version of Qiskit O3 for all experiments. In theory, a different version of Qiskit's optimization shouldn't affect our conclusion, because Qiskit O3 would not observe the canceling opportunity in UCCSD. Could you please share your results here? What is the percentage of outperformance for Qiskit 0.46.1?
> 
> Sure. Can I share my testing results to your email? Previously I guessed it is OS-related disparity when I run it on Windows and Linux. Now I believe it is Qiskit version-related disparity QAQ.

If you sent the results to my email, please notify me in this issue. Just want to double-check so I won't miss your results.

**Comment by Youngcius** [comment]
> > > Thank you for pointing it out. I have no clue about this phenomenon. For fair comparisons, we stick to the same version of Qiskit O3 for all experiments. In theory, a different version of Qiskit's optimization shouldn't affect our conclusion, because Qiskit O3 would not observe the canceling opportunity in UCCSD. Could you please share your results here? What is the percentage of outperformance for Qiskit 0.46.1?
> > 
> > 
> > Sure. Can I share my testing results to your email? Previously I guessed it is OS-related disparity when I run it on Windows and Linux. Now I believe it is Qiskit version-related disparity QAQ.
> 
> If you sent the results to my email, please notify me in this issue. Just want to double-check so I won't miss your results.

Hi. Apologize for my late response. I just sent related files and screenshots to your email.

**Comment by abclzr** [comment]
Hi, I tested this with Qiskit 1.1.0 and observed even worse performance compared to the results in the paper using Qiskit 0.43.2. It seems that Qiskit 1.x is still under development and may not yet include some of the optimization modules available in the pre-1.0 versions during the transpilation phase. While the Qiskit version does impact the results, we use it at the final stage of compilation to uncover optimization opportunities missed by Paulihedral and Tetris. To better assess the performance gap, you could try comparing the results without applying Qiskit O3 or stick to one specific version of qiskit.

**Comment by Youngcius** [comment]
Yeah. While sometimes I found Qiskit 1.x performs better in some situations when appended such an industrial optimization pass to my customized compilers in my research. That is really confusing. On the other hand, I found O2 performs gate inverse cancellation in Qiskit 1.x while that does not perform that in Qiskti 0.xx.
